# Generated by Django 4.1.9 on 2023-05-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docpi_app', '0004_alter_user_email_alter_user_password_alter_user_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='email_index'),
        ),
    ]
