# Generated by Django 4.1.9 on 2023-05-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docpi_app', '0005_user_email_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('shape', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docpi_app.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='documents',
            index=models.Index(fields=['name'], name='name_index'),
        ),
    ]
