# Generated by Django 4.1.9 on 2023-05-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docpi_app', '0007_alter_documents_userdetails'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documents',
            name='name_index',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='email_index',
        ),
    ]
