# Generated by Django 4.1.9 on 2023-05-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docpi_app', '0008_remove_documents_name_index_remove_user_email_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='userDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docpi_app.user'),
        ),
    ]
